### ISSUE TITLE
About page url is not accessible

### ISSUE THREAD

**Issue by eric15342335** [Teinc3/teinc3.github.io#4]
Hi. If I want to see your "About Me" page, I go to your website https://teinc3.github.io, then click the "About Me" button.
I wonder if the steps can be fewer.
Since by pressing the "About Me" button, the browser address bar changes to "https://teinc3.github.io/about", I assume your "About Me" page can be reached by going to the link "https://teinc3.github.io/about" directly.
However, this is not the case, as the website returned me with a 404 Page not found.

**Comment by Teinc3** [comment]
Hi - thanks for raising the issue.

Github Pages does not support server-side rendering. If you access the root page of the website first then go to the about page through pressing button, the about page is loaded from the client side Router. But when you access the about page directly using the link, Github believes that it is a page of a repository of mine named "about", and tries to display such a page but fails, hence the 404 error.

I'm currently busy with other projects and don't have time to update my personal website, and so the error will probably remain for a while until I refactor it. The website is really just an experiment with React as I never used any declarative programming technologies before and am eager to try out new things.
